"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var luchador_1 = require("./luchador");
var mago_1 = require("./mago");
var arquero_1 = require("./arquero");
var asesino_1 = require("./asesino");
var curandero_1 = require("./curandero");
var juego_1 = require("./juego");
var juego = new juego_1.Juego();
//   se declaran 5 argumentos  nombre,nivel, salud, fuerza de dañoy poder especial
var luchador = new luchador_1.Luchador(" El luchador Thor", 1, 100, 25, "Espada");
var mago = new mago_1.Mago("El Mago Gandalf", 1, 100, 20, "Fuego");
var arquero = new arquero_1.Arquero("El Arquero Charles", 1, 100, 30, "Arco");
var asesino = new asesino_1.Asesino("El Asesino Raider", 1, 100, 40, "Veneno mortal");
var curandero = new curandero_1.Curandero("El curandero Jacobo", 1, 100, 35, "Poción de vida");
juego.agregarPersonaje(luchador);
juego.agregarPersonaje(mago);
juego.agregarPersonaje(arquero);
juego.agregarPersonaje(asesino);
juego.agregarPersonaje(curandero);
juego.iniciarJuego();
arquero.encontrarCajaMagica();
arquero.mostrarHabilidades();
console.log("----El Arquero está preparado para contraatacar----\n");
console.log("El Luchador evolucionó");
console.log(luchador);
luchador.setArma("Espada de Fuego");
luchador.setNivel(2);
console.log(luchador);
console.log("---------------!Nivel y arma cambiado con exito¡----\n");
